set(SOURCES
	include/RE/A/Actor.h
	include/RE/A/ActorValueInfo.h
	include/RE/A/ActorValueOwner.h
	include/RE/A/ActorValues.h
	include/RE/B/BGSAttackDataForm.h
	include/RE/B/BGSDestructibleObjectForm.h
	include/RE/B/BGSEditorID.h
	include/RE/B/BGSEntryPoint.h
	include/RE/B/BGSForcedLocRefType.h
	include/RE/B/BGSKeyword.h
	include/RE/B/BGSKeywordForm.h
	include/RE/B/BGSListForm.h
	include/RE/B/BGSLocalizedString.h
	include/RE/B/BGSLocation.h
	include/RE/B/BGSLocationRefType.h
	include/RE/B/BGSMod.h
	include/RE/B/BGSNativeTerminalForm.h
	include/RE/B/BGSObjectPlacementDefaults.h
	include/RE/B/BGSOverridePackCollection.h
	include/RE/B/BGSPerk.h
	include/RE/B/BGSPerkRankArray.h
	include/RE/B/BGSPreviewTransform.h
	include/RE/B/BGSPropertySheet.h
	include/RE/B/BGSScene.h
	include/RE/B/BGSSkinForm.h
	include/RE/B/BGSSnapTemplateComponent.h
	include/RE/B/BGSTerminal.h
	include/RE/B/BSAnimNoteListener.h
	include/RE/B/BSFixedString.h
	include/RE/B/BSInputEventReceiver.h
	include/RE/B/BSIntrusiveRefCounted.h
	include/RE/B/BSReflection.h
	include/RE/B/BSStringPool.h
	include/RE/B/BSStringT.h
	include/RE/B/BSTEvent.h
	include/RE/B/BSTList.h
	include/RE/B/BSTSingleton.h
	include/RE/B/BaseFormComponent.h
	include/RE/C/CombatGroup.h
	include/RE/C/ConsoleLog.h
	include/RE/E/ExtraDataTypes.h
	include/RE/F/FORM_ENUM_STRING.h
	include/RE/F/FormTypes.h
	include/RE/I/IAnimationGraphManagerHolder.h
	include/RE/I/IFunction.h
	include/RE/I/IKeywordFormBase.h
	include/RE/I/IMovementInterface.h
	include/RE/I/INIPrefSettingCollection.h
	include/RE/I/INISettingCollection.h
	include/RE/I/IPostAnimationChannelUpdateFunctor.h
	include/RE/M/MemoryManager.h
	include/RE/M/MenuOpenCloseEvent.h
	include/RE/N/NativeFunction.h
	include/RE/N/NativeFunctionBase.h
	include/RE/N/NiPoint3.h
	include/RE/Offsets.h
	include/RE/Offsets_NiRTTI.h
	include/RE/Offsets_RTTI.h
	include/RE/Offsets_VTABLE.h
	include/RE/P/PlayerCamera.h
	include/RE/R/RegSettingCollection.h
	include/RE/RTTI.h
	include/RE/S/Script.h
	include/RE/S/SettingCollection.h
	include/RE/S/SettingCollectionList.h
	include/RE/S/SettingCollectionMap.h
	include/RE/S/Settings.h
	include/RE/Starfield.h
	include/RE/T/TBO_InstanceData.h
	include/RE/T/TESAIForm.h
	include/RE/T/TESActorBase.h
	include/RE/T/TESActorBaseData.h
	include/RE/T/TESBoundAnimObject.h
	include/RE/T/TESBoundObject.h
	include/RE/T/TESCamera.h
	include/RE/T/TESContainer.h
	include/RE/T/TESFile.h
	include/RE/T/TESForm.h
	include/RE/T/TESFormRefCount.h
	include/RE/T/TESFullName.h
	include/RE/T/TESHandleForm.h
	include/RE/T/TESNPC.h
	include/RE/T/TESObject.h
	include/RE/T/TESObjectARMO.h
	include/RE/T/TESObjectCELL.h
	include/RE/T/TESObjectREFR.h
	include/RE/T/TESQuest.h
	include/RE/T/TESRace.h
	include/RE/T/TESRaceForm.h
	include/RE/T/TESResponse.h
	include/RE/T/TESSpellList.h
	include/RE/T/TESTopicInfo.h
	include/RE/T/TESWorldSpace.h
	include/RE/U/UI.h
	include/REL/ID.h
	include/REL/Module.h
	include/REL/Offset.h
	include/REL/Relocation.h
	include/REL/Version.h
	include/SFSE/API.h
	include/SFSE/IAT.h
	include/SFSE/Impl/DInputAPI.h
	include/SFSE/Impl/PCH.h
	include/SFSE/Impl/Stubs.h
	include/SFSE/Impl/WinAPI.h
	include/SFSE/Impl/XInputAPI.h
	include/SFSE/InputMap.h
	include/SFSE/Interfaces.h
	include/SFSE/Logger.h
	include/SFSE/SFSE.h
	include/SFSE/Trampoline.h
	include/SFSE/Utilities.h
	include/SFSE/Version.h
	src/RE/A/Actor.cpp
	src/RE/A/ActorValueInfo.cpp
	src/RE/A/ActorValueOwner.cpp
	src/RE/A/ActorValues.cpp
	src/RE/B/BGSAttackDataForm.cpp
	src/RE/B/BGSDestructibleObjectForm.cpp
	src/RE/B/BGSForcedLocRefType.cpp
	src/RE/B/BGSKeyword.cpp
	src/RE/B/BGSKeywordForm.cpp
	src/RE/B/BGSListForm.cpp
	src/RE/B/BGSLocation.cpp
	src/RE/B/BGSLocationRefType.cpp
	src/RE/B/BGSMod.cpp
	src/RE/B/BGSNativeTerminalForm.cpp
	src/RE/B/BGSObjectPlacementDefaults.cpp
	src/RE/B/BGSOverridePackCollection.cpp
	src/RE/B/BGSPerk.cpp
	src/RE/B/BGSPerkRankArray.cpp
	src/RE/B/BGSPreviewTransform.cpp
	src/RE/B/BGSPropertySheet.cpp
	src/RE/B/BGSScene.cpp
	src/RE/B/BGSSkinForm.cpp
	src/RE/B/BGSSnapTemplateComponent.cpp
	src/RE/B/BGSTerminal.cpp
	src/RE/B/BSFixedString.cpp
	src/RE/B/BSIntrusiveRefCounted.cpp
	src/RE/B/BSReflection.cpp
	src/RE/B/BSStringT.cpp
	src/RE/B/BSTEvent.cpp
	src/RE/B/BSTList.cpp
	src/RE/B/BaseFormComponent.cpp
	src/RE/C/CombatGroup.cpp
	src/RE/C/ConsoleLog.cpp
	src/RE/F/FormTypes.cpp
	src/RE/I/IAnimationGraphManagerHolder.cpp
	src/RE/I/IFunction.cpp
	src/RE/I/IKeywordFormBase.cpp
	src/RE/I/IMovementInterface.cpp
	src/RE/I/INIPrefSettingCollection.cpp
	src/RE/I/INISettingCollection.cpp
	src/RE/I/IPostAnimationChannelUpdateFunctor.cpp
	src/RE/M/MemoryManager.cpp
	src/RE/M/MenuOpenCloseEvent.cpp
	src/RE/N/NativeFunction.cpp
	src/RE/N/NativeFunctionBase.cpp
	src/RE/N/NiPoint3.cpp
	src/RE/P/PlayerCamera.cpp
	src/RE/R/RegSettingCollection.cpp
	src/RE/S/Script.cpp
	src/RE/S/SettingCollection.cpp
	src/RE/S/SettingCollectionList.cpp
	src/RE/S/SettingCollectionMap.cpp
	src/RE/S/Settings.cpp
	src/RE/Starfield.cpp
	src/RE/T/TBO_InstanceData.cpp
	src/RE/T/TESAIForm.cpp
	src/RE/T/TESActorBase.cpp
	src/RE/T/TESActorBaseData.cpp
	src/RE/T/TESBoundAnimObject.cpp
	src/RE/T/TESBoundObject.cpp
	src/RE/T/TESCamera.cpp
	src/RE/T/TESContainer.cpp
	src/RE/T/TESFile.cpp
	src/RE/T/TESForm.cpp
	src/RE/T/TESFormRefCount.cpp
	src/RE/T/TESFullName.cpp
	src/RE/T/TESHandleForm.cpp
	src/RE/T/TESNPC.cpp
	src/RE/T/TESObject.cpp
	src/RE/T/TESObjectARMO.cpp
	src/RE/T/TESObjectCELL.cpp
	src/RE/T/TESObjectREFR.cpp
	src/RE/T/TESQuest.cpp
	src/RE/T/TESRace.cpp
	src/RE/T/TESRaceForm.cpp
	src/RE/T/TESResponse.cpp
	src/RE/T/TESSpellList.cpp
	src/RE/T/TESTopicInfo.cpp
	src/REL/ID.cpp
	src/REL/Module.cpp
	src/REL/Version.cpp
	src/SFSE/API.cpp
	src/SFSE/IAT.cpp
	src/SFSE/Impl/PCH.cpp
	src/SFSE/Impl/WinAPI.cpp
	src/SFSE/InputMap.cpp
	src/SFSE/Interfaces.cpp
	src/SFSE/Logger.cpp
	src/SFSE/Trampoline.cpp
)
